name: Build Package

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    name: ${{ matrix.os }} / pip / ${{ matrix.qt }} / pyvista-${{ matrix.pyvista }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Build package
        run: |
          python setup.py sdist
  
      - name: lint package
        run: |
          pip install twine
          twine check dist/*

      - name: Install package
        run: |
          pip install dist/*.tar.gz --disable-pip-version-check

      - name: Unit testing
        run: |
          pip install -r requirements_tests.txt --disable-pip-version-check
          pytest -v

      - name: Upload to PyPi
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          pip install twine
          twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}

  conda:
    name: Conda build and publish
    runs-on: 'ubuntu-latest'

    defaults:
      run:
        shell: bash
     
    steps: 
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Installing Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-conda: true

      - name: Installing Conda-build
        run: conda install conda-build
      
      - name: Getting the skeleton
        run: conda skeleton pypi ansys-tools-protos-generator
      
      - name: Building and upload Conda packages
        run: conda build . --quiet --skip-existing --no-test --output-folder OUTPUT_FOLDER --token ${{ secrets.ANACONDA_TOKEN }}
      
      # - name: Generating all files for all archs
      #   run: |
      #     conda convert --platform all ~/anaconda/conda-bld/linux-64/click-7.0-py37_0.tar.bz2 -o outputdir/
      
      # - name: Upload to Anaconda
      #   run: |

